#server:
#  port: 9000
#server:
#  context-path: /lookup-definition-service
spring:
#  config:
#    name: lookup-definition-service
  datasource:
    url: jdbc:hsqldb:mem:webrobot
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.HSQLDialect
  output:
    ansi:
      enabled: always
#  main:
#    web-environment: false
      
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/webrobot
    username: webrobot
    password: aKSXHHxZDxs7sNaW
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
