server:
  port: 4002
spring:
  datasource:
    url: jdbc:hsqldb:mem:webrobot
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.HSQLDialect
  output:
    ansi:
      enabled: always
  cloud:
    stream:
      bindings:
        new-lookup-definitions:
          content-type: application/json
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/webrobot
    username: webrobot
    password: aKSXHHxZDxs7sNaW
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
